name: generate-readme-for-repos
author: gendloop
description: 'generate-readme-for-repos'
inputs:
  file_in:
    description: 'repos.json to read'
    required: false
    default: 'repos.json'
  file_out:
    description: 'file to out'
    required: false
    default: 'README.md'
  label:
    description: 'Label'
    required: false
    default: 'Repos'

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    - name: get-repo-name
      id: get-repo-name
      shell: bash
      run: |
        repo_name=${GITHUB_REPOSITORY#*/}
        echo "reponame=$repo_name" >> "$GITHUB_OUTPUT"

    - name: generate-readme-for-repos
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        ${{ github.action_path }}/scripts/generate_readme_for_repos.ps1 ${{ inputs.file_in }} ${{ inputs.file_out }} ${{ inputs.label }} ${{ steps.get-repo-name.outputs.reponame }} ${{ github.repository_owner }}

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "chore: generate ${{ inputs.file_out }} for ${{ inputs.file_in }} "
